#!/usr/bin/env python
# -*- coding: utf-8 -*- #
from __future__ import unicode_literals

AUTHOR = u'Tadesse Zemicheal'
SITENAME = u'Tadeze in ML'
SITEURL = 'http://tadeze.github.io'

PATH = 'content'

TIMEZONE = 'America/Vancouver'

DEFAULT_LANG = u'en'
THEME='theme/pelican-bootstrap3'
# Feed generation is usually not desired when developing
FEED_ALL_ATOM = None
CATEGORY_FEED_ATOM = None
TRANSLATION_FEED_ATOM = None
AUTHOR_FEED_ATOM = None
AUTHOR_FEED_RSS = None

# Blogroll
LINKS = (('R-blogger', 'http://r-blogger.com/'),
         ('Hutch', 'http://hutch.net/'),
         ('Jinja2', 'http://jinja.pocoo.org/'),
         ('yhat blog', 'blog.yhathq.com'))

# Social widget
SOCIAL = (('Twitter', 'https://twitter.com/tadeze'),
          ('Github', 'http://github.com/tadeze'),
	  ('Linkedin','https://www.linkedin.com/in/tadessehabtemariam'))	
DEFAULT_PAGINATION = 5

# Uncomment following line if you want document-relative URLs when developing
#RELATIVE_URLS = True
